### ISSUE TITLE
[WIP] Rewrite

### ISSUE THREAD

**Issue by airesvsg** [airesvsg/acf-to-rest-api#47]
- [x] remove acf logic of controller | Methods: [L134](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-controller.php#L134), [L163](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-controller.php#L163), [L191](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-controller.php#L191), [L232](https://github.com/airesvsg/acf-to-rest-api/blob/master/lib/endpoints/class-acf-to-rest-api-controller.php#L232)
- [x] multiple custom options pages https://github.com/airesvsg/acf-to-rest-api/issues/85
- [x] change return when acf field key is empty https://github.com/airesvsg/acf-to-rest-api/issues/48
- [x] fix taxomy filter https://github.com/airesvsg/acf-to-rest-api/issues/43
- [x] more readable endpoints https://github.com/airesvsg/acf-to-rest-api/issues/46
